Hsuan_finish documentation
C-KLex/GitEducation pull request #2
Opened 2023-06-22 19:28 UTC by tejkoiejgns

create description and template for commit name, comment, function, module, script, and packages.

2023-06-22 20:25 UTC, YLee2121 commented on documentation_guide.md
> +### *Template for python*:
change to "Template for the python script"

2023-06-22 20:26 UTC, YLee2121 commented on documentation_guide.md
> +Date: [Date]
change to "Date: [Script Create Date]"

2023-06-22 20:26 UTC, YLee2121 commented on documentation_guide.md
> +# Class definitions
remove this line since there is a description under the `class MyClass`

2023-06-22 20:27 UTC, YLee2121 commented on documentation_guide.md
> +# Function definitions and descriptions
Remove this line since function description is under `def my_function()`

2023-06-22 20:29 UTC, YLee2121 commented on documentation_guide.md
> +## 3️⃣ **Xcode Document(.md)**
I don't understand this title since we are not using Xcode and please explain what this section is about.

2023-06-22 20:31 UTC, YLee2121 commented on documentation_guide.md
> +  - *template*:
I am confused by this template, I don't understand when I should implement.

2023-06-22 20:32 UTC, YLee2121 commented on documentation_guide.md
> +- ### **Module description**
FYI, in Python, a script is equal to a module. Please integrate the section with `script` section.

2023-06-22 20:35 UTC, YLee2121 requested changes
@tejkoiejgns 

Good job on the first PR! I need you to do some adjustments! 

Moreover, in the future, please follow the branch name guideline to name the branch. In the guideline, the current branch `hsuan` should be `hsuan\docGuideline`.

About the PR title, name a more meaningful title name such as `Documentation Guideline`.

Rmb to assign the reviewer, add labels, and add the assignee.

2023-06-23 12:24 UTC, tejkoiejgns commented on documentation_guide.md
> +### *Template for python*:
ok

2023-06-23 12:25 UTC, tejkoiejgns commented on documentation_guide.md
> +# Class definitions
ok

2023-06-23 12:25 UTC, tejkoiejgns commented on documentation_guide.md
> +Date: [Date]
ok

2023-06-23 12:26 UTC, tejkoiejgns commented on documentation_guide.md
> +# Function definitions and descriptions
ok

2023-06-23 12:28 UTC, tejkoiejgns commented on documentation_guide.md
> +## 3️⃣ **Xcode Document(.md)**
i just copy the title from https://github.com/C-KLex/GymBro/blob/main/GuideLines.md#documentation-guideline

But i thought it's just the document(markdown) or readme.

2023-06-23 12:28 UTC, tejkoiejgns commented on documentation_guide.md
> +## 3️⃣ **Xcode Document(.md)**
renamed as ## 3️⃣ ** Document(.md)**

2023-06-23 12:33 UTC, tejkoiejgns commented on documentation_guide.md
> +- ### **Module description**
okay

2023-06-23 12:37 UTC, tejkoiejgns commented
ok thanks!  i used git branch -m hsuan\docGuideline to rename my branch

2023-06-23 12:42 UTC, tejkoiejgns commented on documentation_guide.md
> +  - *template*:
a template for explaining our function. 
including:
1. function
2. what the function for 
3. parameters 
4. return

2023-06-23 16:02 UTC, YLee2121 commented on documentation_guide.md
> +  - *template*:
What will the template be located in? Which document do you mean?

2023-06-24 14:15 UTC, tejkoiejgns commented on documentation_guide.md
> +  - *template*:
I thought it may be in README.md file

2023-06-24 16:45 UTC, YLee2121 commented
test one two three

2023-06-24 16:50 UTC, YLee2121 requested changes
The change

2023-06-24 16:50 UTC, YLee2121 commented on documentation_guide.md
> +## 3️⃣ **Document(.md)**
Let me clarify the Document section in the reference Guideline. In XCode editor, it has a unique internal way to write the complete script documentation. However, VScode does not have the same service. 

So I'd like to know what you mean `Document` in this section.

2023-06-24 16:50 UTC, YLee2121 commented on documentation_guide.md
> +## 1️⃣ **Write commit**
Please remove the commit section because it should be with other git-related guidelines located in a different file.

2023-06-24 16:50 UTC, YLee2121 commented on documentation_guide.md
> +## 2️⃣ **Code comment(.py)**
You only define the long comment by using `""" """`.

Please define some one-line comment with `#`.

For example:

```python

for i in range(3):
    
    # do this
    do_something()

    # do that
    # if you need to write more comment
    # just write more line
    do_something2()
```

Key Points:

1. have one line space above `#`
2. avoid comments if the code is enough readable

2023-06-24 16:50 UTC, YLee2121 commented on documentation_guide.md
> +```
I think you can summarize when to use the two types of comments, `#` and `""" """`.

---

For class, function, and script explanation. Use `""" """`, and it's mandatory to write documentation for these scenarios.

For other usage, use `#` and maintain as short a comment as possible.

---

Please summarize and organize this information and add a section for them.

2023-06-24 16:50 UTC, YLee2121 commented on documentation_guide.md
> +```
test comment here 
@tejkoiejgns

2023-06-24 16:50 UTC, YLee2121 commented on documentation_guide.md
> +```
here

2023-06-26 02:17 UTC, tejkoiejgns commented on documentation_guide.md
> +## 2️⃣ **Code comment(.py)**
ok

2023-06-26 02:17 UTC, tejkoiejgns commented on documentation_guide.md
> +## 1️⃣ **Write commit**
ok

2023-06-26 02:19 UTC, tejkoiejgns commented on documentation_guide.md
> +## 3️⃣ **Document(.md)**
i thought it was the README.md content.

2023-06-26 02:20 UTC, tejkoiejgns commented on documentation_guide.md
> +```
ok

2023-06-26 04:13 UTC, YLee2121 commented on documentation_guide.md
> +## 3️⃣ **Document(.md)**
At this point, we won't write the detail package documentation!

2023-06-26 04:18 UTC, YLee2121 approved these changes
approve

2023-06-26 04:19 UTC, merged