Viet+ziqi
C-KLex/GitEducation pull request #3
Opened 2023-06-22 19:29 UTC by Dazeofcitywalk

First version of the code style and naming

2023-06-22 20:40 UTC, YLee2121 commented on code_style_and_naming.md
> +### Whitespace
Add code example

2023-06-22 20:40 UTC, YLee2121 commented on code_style_and_naming.md
> +### Vertical whitespace
code example

2023-06-22 20:41 UTC, YLee2121 commented on code_style_and_naming.md
> +### Parentheses
code example

2023-06-22 20:41 UTC, YLee2121 commented on code_style_and_naming.md
> +### Braces
code example

2023-06-22 20:42 UTC, YLee2121 commented on code_style_and_naming.md
> +    1. No whitespace:
btw, this way to indent the paragraph will cause the black background

please open the previewer while working on the MD file.

2023-06-22 20:43 UTC, YLee2121 commented on code_style_and_naming.md
> +### Properties
Don't add the whole paragraph to the guideline, please give the key point and the example. Please always think that the guideline will be read by yourself and all the team in the future.

2023-06-22 20:44 UTC, YLee2121 commented on code_style_and_naming.md
> +### Switch statements
same issue as above. Wrongly indention would cause the black background. Need example and key point.

2023-06-22 20:45 UTC, YLee2121 commented on code_style_and_naming.md
> +### Enum cases
remove Enum section because Python has no Enum type

2023-06-22 20:45 UTC, YLee2121 commented on code_style_and_naming.md
> +### Trailing commas
I don't think we will need a trailing commas because Python doesn't require commas

2023-06-22 20:49 UTC, YLee2121 commented on code_style_and_naming.md
> +# Naming convention
please don't copy the reference and paste it here. 

The naming convention is for `swift` language. 

For Python, this is the recommended convention. 

* Package: Snake_Case (Uppercase Initial)

* Files: Snake_Case (Uppercase Initial)

* Class: Snake_Case (Uppercase Initial)

* Function: snake_case 

* Variables: snake_case

2023-06-22 20:56 UTC, YLee2121 requested changes
About the coding style, please try to think about the scenario that you are coding. The reference is for you to know how to write the guideline; it's not the resource that you write the guideline based on it.

---

Add a section to show the script structure style. 

Something like this, 

```python

import External_Package

import Internal_Package

Class StartCoding:
   
    def a():
        pass 

    def b():
        pass

if __name__ == "__main__":
    
    # if you need to run code under the script
    run()
```

---

This is what I mean wrongly indention could bring redundant black background. 

![image](https://github.com/C-KLex/GitEducation/assets/87312700/8f7d3c41-c825-4127-989d-18a58cec4597)


---

In the future, please follow the following tips. 

1. Follow the branch name guideline; in this case, your current branch name should be `viet/styleGuide`

2. Remember to add reviewers, labels, and assignees. 

3. Name a meaningful PR title rather than just `Viet+ziqi`

2023-06-23 05:25 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +### Whitespace
added

2023-06-23 05:26 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +### Vertical whitespace
added example for single blank line
for multiple blank lines, I think it depends on specific situations

2023-06-23 05:26 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +### Parentheses
added

2023-06-23 05:28 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +### Braces
Currently I'd like to delete this part (but not sure)
I find myself thinking of C++ and R language, which use braces as the border of function definition. But in Python, I think we use line break instead.

2023-06-23 05:29 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +    1. No whitespace:
Thanks for notice. I have changed it to normal background with some hyphens to express in a clear way.

2023-06-23 05:30 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +# Naming convention
Modified

2023-06-23 13:56 UTC, viettran15 commented on code_style_and_naming.md
> +### Enum cases
Done

2023-06-23 13:56 UTC, viettran15 commented on code_style_and_naming.md
> +### Trailing commas
I've removed this section entirely

2023-06-23 14:41 UTC, YLee2121 commented on code_style_and_naming.md
> +### Braces
Yes, go ahead and delete

2023-06-23 14:42 UTC, YLee2121 commented on code_style_and_naming.md
> +### Enum cases
@viettran15 
but it's still here, i think you forget to push to the cloud

2023-06-23 14:42 UTC, YLee2121 commented on code_style_and_naming.md
> +### Trailing commas
@viettran15
but it's still here, i think you forget to push to the cloud

2023-06-23 15:38 UTC, viettran15 commented on code_style_and_naming.md
> +### Properties
I've added examples for the specific key points.

2023-06-23 15:38 UTC, viettran15 commented on code_style_and_naming.md
> +### Switch statements
I've updated the indenting as well as adding examples to the key points.

2023-06-23 15:41 UTC, YLee2121 commented on code_style_and_naming.md
> +### Vertical whitespace
You can define the situation if needed.

2023-06-23 15:43 UTC, YLee2121 commented on code_style_and_naming.md
> +### Properties
Have you pushed the commit to the cloud?

It seems that the file has not been updated yet.

2023-06-23 15:43 UTC, YLee2121 commented on code_style_and_naming.md
> +### Switch statements
Have you pushed the commit to the cloud?

It seems that the file has not been updated yet.

2023-06-23 15:46 UTC, YLee2121 commented on code_style_and_naming.md
> +### Switch statements
I see the change! No worry!

2023-06-23 15:46 UTC, YLee2121 commented on code_style_and_naming.md
> +### Trailing commas
I see the change! No worry!

2023-06-23 15:46 UTC, YLee2121 commented on code_style_and_naming.md
> +### Enum cases
I see the change! No worry!

2023-06-23 15:46 UTC, YLee2121 commented on code_style_and_naming.md
> +### Properties
I see the change! No worry!

2023-06-23 15:51 UTC, YLee2121 commented on code_style_and_naming.md
> +2. Start each case label on a new line and indent it one level deeper than the switch statement. Additionally, align the case labels vertically for better readability.
For point 2 and point 3, could you integrate into one example? It is confusing that there are two styles of python `switch` examples.

2023-06-23 15:53 UTC, YLee2121 commented on code_style_and_naming.md
> +        function1(var1, var2)
don't write `function1(var1, var2)`, instead, write `def function1(var1, var2)` due to the Python syntax.

2023-06-23 15:55 UTC, YLee2121 commented on code_style_and_naming.md
> +## Specific guideline
Uppercase for the first letter. 

change to `Specific Guideline`

2023-06-23 15:56 UTC, YLee2121 commented on code_style_and_naming.md
> +### Vertical whitespace
Uppercase for the first letter of the title.

Change into `Vertical Whitespace`

2023-06-23 15:57 UTC, YLee2121 commented on code_style_and_naming.md
> +# Coding style guideline
Uppercase for the first letter in the title.

Change into `Coding Style Guideline`

2023-06-23 15:57 UTC, YLee2121 commented on code_style_and_naming.md
> +## General guideline
Uppercase for the first letter in the title.

Change into `General Guideline`

2023-06-23 16:00 UTC, YLee2121 commented on code_style_and_naming.md
> +
At the end of the General Guideline. 

Add a section to show the CORRECT example script following the guideline.

Something like this, 

```python

import External_Package

import Internal_Package

Class StartCoding:
   
    def a():
        pass 

    def b():
        pass

if __name__ == "__main__":
    
    # if you need to run code under the script
    run()
```

Please really write a functional example code following the General Guidelines.

2023-06-23 16:12 UTC, YLee2121 commented on code_style_and_naming.md
Add a section in the general guideline to define the `function` guideline.

Here are two cases.

```python
def a(a: int, b: int) -> None():

    # some code here

    return 

def func(a: list, b: dict) -> str():

    # some code here

    return "hi"
```

Here are the key points:

1. Parameter Type

    Write down the input parameter data type.

2. Return Type

    Write down the return data type.

4. Always Return

    Write down return even if it returns nothing.

2023-06-23 17:44 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +### Vertical whitespace
Thanks, I have removed this part already

2023-06-23 17:44 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +### Braces
thanks, I have removed this part already

2023-06-23 17:44 UTC, Dazeofcitywalk commented on code_style_and_naming.md
> +### Vertical whitespace
Modified

2023-06-23 20:39 UTC, viettran15 commented on code_style_and_naming.md
> +2. Start each case label on a new line and indent it one level deeper than the switch statement. Additionally, align the case labels vertically for better readability.
Yes, I've combined these 2 points into 1.

2023-06-23 20:39 UTC, viettran15 commented on code_style_and_naming.md
> +        function1(var1, var2)
This has been updated in the file.

2023-06-23 20:39 UTC, viettran15 commented on code_style_and_naming.md
> +## Specific guideline
Done

2023-06-23 20:40 UTC, viettran15 commented on code_style_and_naming.md
> +### Vertical whitespace
Done

2023-06-23 20:40 UTC, viettran15 commented on code_style_and_naming.md
> +# Coding style guideline
Done

2023-06-23 20:40 UTC, viettran15 commented on code_style_and_naming.md
> +## General guideline
Done

2023-06-23 21:03 UTC, YLee2121 commented
@viettran15 please remember to follow the commit guideline in the future's commit

2023-06-23 21:08 UTC, YLee2121 commented on code_style_and_naming.md
> +
@Dazeofcitywalk @viettran15 remember this one

2023-06-23 21:08 UTC, YLee2121 commented on code_style_and_naming.md
@Dazeofcitywalk @viettran15 remember this one

2023-06-24 16:55 UTC, YLee2121 requested changes
Good Job! And FYI, there are several comments needed to be fixed. The file is almost finished!

2023-06-24 19:43 UTC, Dazeofcitywalk commented on code_style_and_naming.md
I have combined the previous part "correct example script" with this part, that is to write a sample code with return and types.

2023-06-25 03:09 UTC, YLee2121 approved these changes
# Final Feedback for the Future

@Dazeofcitywalk @viettran15 Thank you for the work on the PR. It's approved, and below is some final feedback for this PR.

## ⚡Commit Naming 

Please strictly follow the commit naming guideline!

## 💪My Change

The below code is what I edit for the example code. 

---

### **CORRECT SCRIPT EXAMPLE (MUST READ)** 👋

```python
import internal_package

import external_package

class foo1:

    def bar1(var1: int, var2: str) -> int():

        # some code

        return 3

    def bar2(var1: str, var2: str) -> None():
        
        # some code

        return

if __name__ == "__main__":

    # some code

```

**Key Point**

1. Script Structure & Order

    - Import external package, e.g `numpy`, `random`

    - Import internal package (package built by developers)

    - Main code

    - Run section (if available)

2. Function Guideline

    - Parameter Type: Write down the input parameter data type

    - Return Type: Write down the return data type

    - Always Return: Write down `return` even if it returns nothing

2023-06-25 03:10 UTC, merged