‘get_week_day()’ First PR
C-KLex/GitEducation pull request #5
Opened 2023-06-26 18:46 UTC by tejkoiejgns

### **Summary**

- Add: get_week_of_day() 
- Description: It returns what week the date is within the year. Every 1/1 to 1/7 of the year will be considered as week 1.
- Example1: 
    - Input: 2020, 1, 1
    - Output: 1
- Example2: 
    - Input: 2021, 12, 8
    - Output: 49

2023-06-26 19:00 UTC, alex308248 commented on Calendar_CLI/Calendar.py
> +        day: from 1 to 31(with exception of Feb)
The day should depends on month and leap year and have different upper bounds. Not only from 1 to 31 except of Feb.

2023-06-26 19:08 UTC, alex308248 requested changes
Great job! It's good to see the function so quick. I believe it's working well when the input is legal. However, you'll also need to handle the edge cases, otherwise the program will crash when user input illegeal dates. For example, what if the user input 1/32/2023 or 2/29/2023 . Do some research on `try` and `except` and handle the edge cases in get_week_day().

2023-06-26 19:15 UTC, tejkoiejgns commented on Calendar_CLI/Calendar.py
> +        day: from 1 to 31(with exception of Feb)
ok! i'll revise the description, but the function itself will detect if the date exist.

2023-06-26 19:23 UTC, alex308248 commented on Calendar_CLI/Calendar.py
> +        day: from 1 to 31(with exception of Feb)
Yup, I know the function will detect if the date do not exist. But it will also crash the program if you do not handle it. I think it will be sad to see your program crash every time when you type wrong input exciddently. A better way is to handle the illegal cases and show an `Illegal Input` alert. 

 
![image](https://github.com/C-KLex/GitEducation/assets/44662448/6bedf1dc-1942-44ec-aab6-2290d69fb3ad)
![image](https://github.com/C-KLex/GitEducation/assets/44662448/d66cafd1-943f-4504-8901-71dd404e35b4)

2023-06-26 19:27 UTC, tejkoiejgns commented on Calendar_CLI/Calendar.py
> +        day: from 1 to 31(with exception of Feb)
oh, got it. I will rewrite the function, let it report the error message and redirect to the input.

2023-06-26 20:44 UTC, alex308248 commented on Calendar_CLI/Calendar.py
> +        day: from 1 to 31(except for Feb, Apr, June, Sep, Nov)
I think it would be better to write a sentence here. For example, you can write something like:

day: depends on month and leap year, from 1 to {28,29,30,31}

2023-06-27 00:12 UTC, tejkoiejgns commented on Calendar_CLI/Calendar.py
> +        day: from 1 to 31(except for Feb, Apr, June, Sep, Nov)
ok it's better! thanks

2023-06-27 01:18 UTC, YLee2121 commented
# Commit Message Feedback

@tejkoiejgns 

![image](https://github.com/C-KLex/GitEducation/assets/87312700/3b9a42ed-a4ca-4a60-ada0-fc5cf0eae983)

For the first commit, don't use `add` but use the `feat`, feature. 

The git commit guideline has an explanation for the labels. 

You don't need to change anything for now, it's just the feedback for your future work.

2023-06-27 01:19 UTC, tejkoiejgns commented
> # Commit Message Feedback
> @tejkoiejgns
> 
> ![image](https://user-images.githubusercontent.com/87312700/249007453-3b9a42ed-a4ca-4a60-ada0-fc5cf0eae983.png)
> 
> For the first commit, don't use `add` but use the `feat`, feature.
> 
> The git commit guideline has an explanation for the labels.
> 
> You don't need to change anything for now, it's just the feedback for your future work.

got it, thanks

2023-06-27 01:23 UTC, alex308248 approved these changes
Approved~~

2023-06-27 01:23 UTC, merged